// aliases.js
// We will expand it later on with GPT to include 
export const aliasCategories = {
    'excuse': [
        "Sorry, was too busy ${randomVerb}ing on ${randomNoun}.",
        "Oops, had to ${randomVerb} some ${randomNoun} in the ${randomObject}.",
        "Got distracted ${randomVerb}ing ${randomNoun} theories on YouTube.",
        "Sorry, my ${randomNoun} just posted something edgy on ${randomObject}.",
        "Was AFK, ${randomVerb}ing ${randomNoun} online.",
        "Lost track of time ${randomVerb}ing at ${randomNoun}.",
        "Had to ${randomVerb} to this ${randomNoun} in the chat, you know.",
        "Was busy setting up a ${randomNoun} to outsmart the ${randomObject}.",
        "My other monitor has a live stream of ${randomNoun}, can't look away.",
        "Sorry, was just ${randomVerb}ing in another ${randomObject}.",
        "Got distracted finding the best ${randomNoun} on the internet.",
        "Was busy ${randomVerb}ing the ${randomNoun}, it's a tough job.",
        "Hold on, was just finishing a ${randomVerb} of '${randomNoun}'.",
        "Sorry, I was busy ${randomVerb}ing fake news on social media.",
        "Was deep in a ${randomNoun} hole, it's a long story.",
        "Had to check on my ${randomNoun} stocks, they're volatile!",
        "Sorry, was busy ${randomVerb}ing the entire ${randomObject}.",
        "Just realized I'm in the ${randomNoun}, had a surreal moment.",
        "Was watching ${randomNoun} videos, they're oddly captivating.",
        "Sorry, had to update my collection of ${randomNoun}.",
        "Accidentally started a flame war over ${randomNoun} in a forum.",
        "Was too engrossed in arguing about ${randomNoun} on Discord.",
        "Sorry, got caught up ${randomVerb}ing an intense round of ${randomObject}.",
        "I was busy moderating a heated debate on ${randomNoun}.",
        "Got lost in the rabbit hole of ${randomNoun} tutorials.",
        "Was stuck on a video call discussing ${randomObject} strategies.",
        "I was deep in thought planning my next ${randomNoun} session.",
        "Sorry, was in the zone theorizing about alternate ${randomObject}.",
        "I was distracted by an intense discussion about ${randomNoun}.",
        "Just finished a marathon session of ${randomVerb}ing ${randomNoun}."
    ],
    'funny': [
        "Why did the ${randomNoun} ${randomVerb} across the road? To get to the ${randomObject}!",
        "I'm not arguing, I'm just ${randomVerb}ing why I'm ${randomNoun}.",
        "I told my ${randomNoun} I was ${randomVerb}ing, but all I got was this ${randomObject}.",
        "Never trust atoms, they make up ${randomObject} ${randomVerb}ing.",
        "I ${randomVerb} a lot of ${randomNoun} jokes, but they are not ${randomObject}.",
        "Parallel lines have so much in common. It’s a shame they’ll never ${randomVerb}ing.",
        "I'd tell you a ${randomObject} joke, but I'm afraid it's not ${randomNoun} enough.",
        "Why don't scientists trust ${randomNouns}? Because they make up ${randomObject}.",
        "I'm reading a book on ${randomVerb}ing gravity. It’s impossible to put down!",
        "Did you hear about the ${randomNoun} who ${randomVerb} into a bar? Ouch.",
        "What do you call a ${randomNoun} without ${randomObject}? Unreliable!",
        "If a ${randomNoun} ${randomVerb}s in a forest, and no one is around to hear it, does it make a ${randomObject}?",
        "I would tell you a UDP joke, but you might not ${randomVerb} it.",
        "Two ${randomNouns} walk into a bar. The bartender says, 'Is this a ${randomObject}?'",
        "I have a joke about ${randomVerb}ing, but it's a bit too ${randomNoun}.",
        "I told my wife she should ${randomVerb} her ${randomObject} – it was a ${randomNoun} choice.",
        "I ${randomVerb} a joke about time travel, but you didn’t ${randomNoun} it.",
        "I'm on a seafood diet. I see ${randomNoun}, and I ${randomVerb} it!",
        "I'm not lazy, I'm just on my ${randomNoun} mode.",
        "Why do ${randomNouns} never start a ${randomVerb}? They don't want to create a scene.",
        "I’d tell you a chemistry joke, but all the good ones ${randomVerb} ${randomObject}.",
        "I’m reading a book on anti-gravity. It’s impossible to put ${randomNoun} down!",
        "What do you call a ${randomNoun} in a ${randomObject}? A ${randomVerb}ing situation.",
        "6:30 is the best time on a ${randomObject}. Hands ${randomVerb}ing.",
        "I ${randomVerb} a joke about construction, but I'm still ${randomNoun}ing on it.",
        "Why don't skeletons ${randomVerb}? They don't have the ${randomNoun}s.",
        "What did the ${randomNoun} say to the ${randomObject}? ${randomVerb}ing you later!",
        "I'm thinking of reasons to ${randomVerb} ${randomNouns}. They’re all pointless.",
        "Why can't you trust stairs? They're always ${randomVerb}ing up to something.",
        "I used to play piano by ${randomNoun}. Now I don’t know where the ${randomObject} is."
    ],
    'whine': [
        "Why do I always have to ${randomVerb}ing with a ${randomNoun} like this?",
        "Ugh, ${randomVerb}ing this ${randomObject} is just impossible!",
        "I can't believe I have to deal with this damn ${randomNoun} again!",
        "Not ${randomVerb}ing well today, this ${randomObject} is so annoying.",
        "Why is my stupid ${randomNoun} always the one that glitches?",
        "Can someone explain why this ${randomObject} won't ${randomVerb} correctly?",
        "I'm tired of always ${randomVerb}ing with these ${randomNoun}s!",
        "This game is so rigged, my freaking ${randomNoun} never works!",
        "I guess I'll just sit here and ${randomVerb}ing with my broken ${randomObject}.",
        "Seriously, another bug in this damn ${randomNoun}?",
        "I'm not ${randomVerb}ing until they fix this shitty ${randomObject}.",
        "My ${randomNoun} is the worst, it never does what I want.",
        "Why does ${randomVerb}ing have to be so hard in this game?",
        "Everyone else has better ${randomNoun}s than me!",
        "It's like this ${randomObject} was designed to make me miserable.",
        "I always get the worst luck with this cursed ${randomNoun}.",
        "I'm just going to ${randomVerb} here and complain about my ${randomObject}.",
        "Nothing ever goes right with this damn ${randomNoun}!",
        "Why can't I just have a normal game without a ${randomObject} issue?",
        "Every time I try to ${randomVerb}, this stupid ${randomNoun} messes up.",
        "I'm so done with trying to deal with this crappy ${randomObject}.",
        "It's not fair, my ${randomNoun} is always the problem.",
        "Why do I always get stuck ${randomVerb}ing this?",
        "Can we just talk about how bad this ${randomObject} is?",
        "I never win because of this stupid ${randomNoun}.",
        "Is it just me, or is ${randomVerb}ing here really bad?",
        "I wish I never had to deal with this goddamn ${randomNoun} again.",
        "Every single time I try to ${randomVerb}, the same ${randomObject} happens.",
        "I'm so sick of this freaking ${randomNoun}, it's always the same issue.",
        "Why does every ${randomVerb}ing session end with a ${randomObject} disaster?"
    ]
    
  };

  export const verbs = [
        "devour", "munch", "gobble", "chomp", "nibble",
        "gnaw", "scarf", "snack", "feast", "guzzle",
        "wolf", "inhal", "savor", "drool", "slurp",
        "crunch", "smack", "lick", "chew", "swallow",
        "burp", "belch", "snarl", "growl", "grumbl",
        "snicker", "sneer", "smirk", "guffaw", "cackl",
        "heckl", "mock", "teas", "taunt", "jeer",
        "squabbl", "bicker", "quarrel", "squawk", "brawl",
        "wrestl", "tussl", "duel", "sparr", "clash",
        "jostl", "shov", "pok", "jabb", "thrust",
        "slapp", "spank", "whipp", "tickl", "tweak",
        "fidget", "wriggl", "twitch", "fiddl", "fumbl",
        "stagger", "stumbl", "toddl", "lurch", "limp",
        "crawl", "creep", "sneak", "prowl", "lurk",
        "skulk", "loiter", "dawdl", "lollygagg", "bumbl",
        "blunder", "stutter", "mutter", "murmur", "babbl",
        "rambl", "yammer", "rant", "rav", "bellow"
  ];

  export const objects = [
        "teacup", "lampshade", "bicycle", "toaster", "sofa",
        "sandwich", "microphone", "skateboard", "laptop", "backpack",
        "toothbrush", "fridge", "guitar", "pillow", "camera",
        "bookshelf", "staircase", "mirror", "bathtub", "broccoli",
        "spaceship", "robot", "unicorn", "dinosaur", "volcano",
        "mother", "father", "step-dad", "step-mom", "grandpa",
        "grandma", "uncle", "aunt", "cousin", "nephew",
        "niece", "brother", "sister", "half-brother", "half-sister",
        "step-brother", "step-sister", "son", "daughter", "godfather",
        "godmother", "boyfriend", "girlfriend", "husband", "wife",
        "fiancé", "fiancée", "ex-boyfriend", "ex-girlfriend", "best friend",
        "roommate", "landlord", "tenant", "chef", "waiter",
        "teacher", "student", "doctor", "nurse", "dentist",
        "policeman", "firefighter", "astronaut", "scientist", "detective",
        "pirate", "wizard", "witch", "vampire", "zombie",
        "ghost", "monster", "alien", "robot", "superhero",
        "villain", "warrior", "knight", "prince", "princess",
        "headset", "mouse", "keyboard", "GPU", "monitor",
        "joystick", "gamepad", "VR headset", "streaming camera", "gaming chair",
        "console", "webcam", "modem", "router", "microSD card",
        "hard drive", "SSD", "CPU", "motherboard", "power supply"
      ];

      export const otherObjects = [
        "dildo", "flux capacitor", "rubber chicken", "wig", "plunger",
        "slinky", "hoverboard", "trombone", "kazoo", "spatula",
        "pogo stick", "hula hoop", "voodoo doll", "fanny pack", "pet rock",
        "mullet wig", "disco ball", "banana peel", "saxophone", "accordion",
        "snorkel", "roller skates", "tutu", "jester hat", "magic wand",
        "gumball machine", "cuckoo clock", "bean bag", "lava lamp", "yo-yo",
        "stink bomb", "whoopie cushion", "squirt gun", "rubber duck", "gnome",
        "tiki torch", "bubble wrap", "velcro", "duct tape", "glitter bomb",
        "whoopee cushion", "slime", "fake mustache", "clown nose", "bowling ball",
        "marshmallow gun", "light saber", "pickle jar", "stuffed unicorn", "shrubbery",
        "noodle", "sponge", "chatter teeth", "water balloon", "air guitar",
        "nerf gun", "candy cane", "soap bar", "pie tin", "pool noodle" ];
  

  